# name: clean-gin-api

# on:
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]

# jobs:
#   build:
#     name: Build the clean_gin_api repository in master
#     runs-on: ubuntu-latest
#     steps:
#       - name: checkout source code
#         uses: actions/checkout@v2
#       - name: Use golang ${{matrix.go-version}}
#         uses: actions/setup-go@v2
#         with:
#           go-version: "1.17"
#       - name: Initialize the environment variables
#         run: |
#           echo "running .env file"
#           echo "SERVER_PORT=9000
#           ENVIRONMENT=local
#           DB_HOST=${{ secrets.DB_HOST }}
#           DB_PORT=3306
#           DB_NAME=${{ secrets.DB_NAME }}
#           DB_USER=${{ secrets.DB_USER }}
#           DB_PASS=${{ secrets.DB_PASS }}
#           MAX_MULTIPART_MEMORY=10485760
#           ADMINER_PORT=5001
#           DEBUG_PORT=5002" >.env
#       - name: testing docker-compose build
#         run: |
#           docker-compose build
#       - run: docker-compose up -d
#       - name: Validate if the service is working or not via health check api
#         run: |
#           sleep 120
#           curl http://localhost:9000/health-check

#       - name: Slack Notification on SUCCESS
#         if:
#           success()
#           # Pick up events even if the job gets success
#         uses: tokorom/action-slack-incoming-webhook@main
#         env:
#           INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#         with:
#           text: A build job on master job for clean_gin_api has succeeded :tada:.
#           attachments: |
#             [
#               {
#                 "color": "good",
#                 "author_name": "${{ github.actor }}",
#                 "author_icon": "${{ github.event.sender.avatar_url }}",
#                 "fields": [
#                   {
#                     "title": "Commit Message",
#                     "value": "${{ github.event.head_commit.message }}"
#                   },
#                   {
#                     "title": "GitHub Actions URL",
#                     "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
#                   },
#                   {
#                     "title": "Compare URL",
#                     "value": "${{ github.event.compare }}"
#                   }
#                 ]
#               }
#             ]
#       - name: Slack Notification on FAILURE
#         if:
#           failure()
#           # Pick up events even if the job fails or is canceled.
#         uses: tokorom/action-slack-incoming-webhook@main
#         env:
#           INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#         with:
#           text: A build  job on master for clean_gin_api has failed :crying_cat_face:.
#           attachments: |
#             [
#               {
#                 "color": "danger",
#                 "author_name": "${{ github.actor }}",
#                 "author_icon": "${{ github.event.sender.avatar_url }}",
#                 "fields": [
#                   {
#                     "title": "Commit Message",
#                     "value": "${{ github.event.head_commit.message }}"
#                   },
#                   {
#                     "title": "GitHub Actions URL",
#                     "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
#                   },
#                   {
#                     "title": "Compare URL",
#                     "value": "${{ github.event.compare }}"
#                   }
#                 ]
#               }
#             ]
